apiVersion: v1
kind: Pod
metadata:
  name: frontend-pod
  labels:
    app: frontend
spec:
  containers:
    - image: chmurka/frontend
      imagePullPolicy: Never
      name: frontend-container
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      readinessProbe:
        httpGet:
          scheme: HTTP
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
