version: "2"
services:
  pg:
    image: postgres:11
    restart: "always"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=movies
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "./db/data:/var/;ib/postgresql/data"
      - "./db/init:/docker-entrypoint-initdb.d"
  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend/:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
  backend:
    build: ./backend
    command: npm run dev
    volumes: 
      - ./backend/:/usr/backend/
    ports:
      - "8000:8000"  
