version: "2"
services:
  postgres:
    image: postgres:11
    restart: "always"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=movies
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "./db/data:/var/;ib/postgresql/data"
      - "./db/init:/docker-entrypoint-initdb.d"
  backend:
    build: ./backend
    command: npm run dev
    volumes:
      - /usr/backend/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  frontend:
    build: ./frontend/Dockerfile.dev
    command: npm run dev
    volumes:
      - ./frontend/:/usr/app/
      - /usr/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - backend
