apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: backend
spec:
  containers:
    - image: postgres
      name: postgres-container
      envFrom:
        - configMapRef:
            name: postgres-config
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
