apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  volumes:
    - name: postgresdb
      persistentVolumeClaim:
        claimName: postgres-pv-claim
  containers:
    - image: postgres
      name: postgres-container
      envFrom:
        - configMapRef:
            name: postgres-config
      ports:
        - containerPort: 5432
          name: http
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresdb
